-- =============================================================================
-- ZafraClic - runtime logs de la app (cliente)
-- Guarda errores/warnings operativos desde la app vía Edge Function autenticada.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.app_runtime_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id UUID,
  actor_role public.rol_usuario,
  level TEXT NOT NULL CHECK (level IN ('info', 'warn', 'error')),
  scope TEXT NOT NULL,
  message TEXT NOT NULL,
  details JSONB,
  app_version TEXT,
  platform TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_app_runtime_logs_actor_created
  ON public.app_runtime_logs(actor_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_app_runtime_logs_created_at
  ON public.app_runtime_logs(created_at DESC);

CREATE INDEX IF NOT EXISTS idx_app_runtime_logs_level_created
  ON public.app_runtime_logs(level, created_at DESC);

ALTER TABLE public.app_runtime_logs ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "app_runtime_logs_actor_select" ON public.app_runtime_logs;
CREATE POLICY "app_runtime_logs_actor_select" ON public.app_runtime_logs FOR SELECT
  USING (auth.uid() = actor_id);

DROP POLICY IF EXISTS "app_runtime_logs_ceo_select" ON public.app_runtime_logs;
CREATE POLICY "app_runtime_logs_ceo_select" ON public.app_runtime_logs FOR SELECT
  USING (public.is_zafra_ceo());

DROP POLICY IF EXISTS "app_runtime_logs_actor_insert" ON public.app_runtime_logs;
CREATE POLICY "app_runtime_logs_actor_insert" ON public.app_runtime_logs FOR INSERT
  WITH CHECK (auth.uid() = actor_id);
