-- =============================================================================
-- NIVEL 3 – search_path en SECURITY DEFINER, audit trigger, soft-delete finca
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. Parchear funciones SECURITY DEFINER sin SET search_path (evita path injection)
-- -----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.fn_actualizar_reputacion()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.perfiles SET
    reputacion   = (SELECT ROUND(AVG(puntaje)::NUMERIC,2) FROM public.calificaciones WHERE evaluado_id = NEW.evaluado_id),
    total_tratos = (SELECT COUNT(*) FROM public.calificaciones WHERE evaluado_id = NEW.evaluado_id)
  WHERE id = NEW.evaluado_id;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.publicar_cosecha(p_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.perfiles WHERE id = auth.uid() AND kyc_estado = 'verified') THEN
    RAISE EXCEPTION 'KYC_REQUERIDO: Debes verificar tu identidad antes de publicar.';
  END IF;
  UPDATE public.cosechas SET estado = 'publicada', publicado_en = NOW()
    WHERE id = p_id AND agricultor_id = auth.uid();
  INSERT INTO public.ticker_items(tipo, texto, estado_ve, prioridad)
    SELECT 'oferta', '🌽 Nueva cosecha: ' || rubro || ' – ' || cantidad_kg || ' kg | ' || municipio, estado_ve, 8
    FROM public.cosechas WHERE id = p_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.cerrar_trato(p_sala UUID, p_precio NUMERIC, p_moneda TEXT DEFAULT 'USD')
RETURNS TABLE(transportista_id UUID, nombre TEXT, distancia_km FLOAT)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE v_coords GEOGRAPHY;
BEGIN
  UPDATE public.salas_chat SET trato_cerrado = TRUE, precio_acordado = p_precio, moneda = p_moneda
    WHERE id = p_sala AND (comprador_id = auth.uid() OR agricultor_id = auth.uid());
  SELECT c.coord_carga INTO v_coords FROM public.salas_chat s JOIN public.cosechas c ON c.id = s.cosecha_id WHERE s.id = p_sala;
  RETURN QUERY
    SELECT p.id, p.nombre, ST_Distance(v_coords, f.origen_coords)::FLOAT / 1000
    FROM public.fletes f JOIN public.perfiles p ON p.id = f.transportista_id
    WHERE f.estado = 'available' AND p.kyc_estado = 'verified'
      AND ST_DWithin(v_coords, f.origen_coords, 30000)
    ORDER BY ST_Distance(v_coords, f.origen_coords) ASC LIMIT 10;
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_inspeccion_sincronizada()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.sincronizado = TRUE AND NOT NEW.aprobado THEN
    UPDATE public.inspecciones SET aprobado = TRUE WHERE id = NEW.id;
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE FUNCTION public.fn_alerta_perito_verificada()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF EXISTS (SELECT 1 FROM public.peritos WHERE perfil_id = NEW.perfil_id) THEN
    NEW.estado := 'verificada';
  END IF;
  RETURN NEW;
END;
$$;

-- -----------------------------------------------------------------------------
-- 2. Tabla de audit log de cambios críticos (enterprise audit trail)
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.cambios_criticos_log (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tabla       TEXT NOT NULL,
  operacion   TEXT NOT NULL CHECK (operacion IN ('INSERT', 'UPDATE', 'DELETE')),
  fila_id     TEXT,
  actor_id    UUID,
  antes       JSONB,
  despues     JSONB,
  creado_en   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_cambios_log_tabla_created
  ON public.cambios_criticos_log(tabla, creado_en DESC);
CREATE INDEX IF NOT EXISTS idx_cambios_log_actor
  ON public.cambios_criticos_log(actor_id, creado_en DESC);

ALTER TABLE public.cambios_criticos_log ENABLE ROW LEVEL SECURITY;

CREATE POLICY "cambios_log_ceo_select" ON public.cambios_criticos_log FOR SELECT
  USING (public.is_zafra_ceo());

-- Función genérica del trigger de audit
CREATE OR REPLACE FUNCTION public.fn_audit_cambio_critico()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_fila_id TEXT;
  v_antes   JSONB;
  v_despues JSONB;
BEGIN
  IF TG_OP = 'DELETE' THEN
    v_fila_id := OLD.id::TEXT;
    v_antes   := to_jsonb(OLD);
    v_despues := NULL;
  ELSIF TG_OP = 'INSERT' THEN
    v_fila_id := NEW.id::TEXT;
    v_antes   := NULL;
    v_despues := to_jsonb(NEW);
  ELSE
    v_fila_id := NEW.id::TEXT;
    v_antes   := to_jsonb(OLD);
    v_despues := to_jsonb(NEW);
  END IF;

  INSERT INTO public.cambios_criticos_log(tabla, operacion, fila_id, actor_id, antes, despues)
  VALUES (TG_TABLE_NAME, TG_OP, v_fila_id, auth.uid(), v_antes, v_despues);

  RETURN COALESCE(NEW, OLD);
END;
$$;

-- Triggers en tablas críticas
DROP TRIGGER IF EXISTS trg_audit_cosechas ON public.cosechas;
CREATE TRIGGER trg_audit_cosechas
  AFTER INSERT OR UPDATE OR DELETE ON public.cosechas
  FOR EACH ROW EXECUTE FUNCTION public.fn_audit_cambio_critico();

DROP TRIGGER IF EXISTS trg_audit_kyc_docs ON public.kyc_docs;
CREATE TRIGGER trg_audit_kyc_docs
  AFTER INSERT OR UPDATE OR DELETE ON public.kyc_docs
  FOR EACH ROW EXECUTE FUNCTION public.fn_audit_cambio_critico();

DROP TRIGGER IF EXISTS trg_audit_perfiles_rol ON public.perfiles;
CREATE TRIGGER trg_audit_perfiles_rol
  AFTER UPDATE OF rol, kyc_estado ON public.perfiles
  FOR EACH ROW
  WHEN (OLD.rol IS DISTINCT FROM NEW.rol OR OLD.kyc_estado IS DISTINCT FROM NEW.kyc_estado)
  EXECUTE FUNCTION public.fn_audit_cambio_critico();

-- -----------------------------------------------------------------------------
-- 3. RPC soft-delete de finca (desactivar en vez de borrar, conserva datos)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.desactivar_finca(p_finca_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.fincas
  SET activa = FALSE
  WHERE id = p_finca_id
    AND propietario_id = auth.uid();

  IF NOT FOUND THEN
    RAISE EXCEPTION 'FINCA_NO_ENCONTRADA: No se encontró la finca o no tienes permiso.';
  END IF;
END;
$$;

REVOKE ALL ON FUNCTION public.desactivar_finca(UUID) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.desactivar_finca(UUID) TO authenticated;
